"
A WIDEEnvironmentTest is a test class for testing the behavior of WIDEEnvironment
"
Class {
	#name : #WIDEEnvironmentTest,
	#superclass : #TestCase,
	#category : #'WIDE-Model-Tests'
}

{ #category : #test }
WIDEEnvironmentTest >> testClassesFor [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
WIDEEnvironmentTest >> testMethodsForUnder [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
WIDEEnvironmentTest >> testPackages [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
WIDEEnvironmentTest >> testProtocolsFor [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
WIDEEnvironmentTest >> testTagsFor [

	self flag: #toImplement.
	self assert: false
]
